version: "3"
services:
  gateway:
    build:
      context: gateway
      dockerfile: Dockerfile
    environment:
      - port=:5000
      - mongo_uri=mongodb://database
    ports:
      - 2865:5000

  recommended:
    build:
      context: recommendation-service
      dockerfile: Dockerfile
    environment:
      - port=:5000
      - mongo_uri=mongodb://database

  interactions:
    build:
      context: interactions
      dockerfile: Dockerfile
    environment:
      - port=:5000
      - mongo_uri=mongodb://database

  data-outlet:
    build:
      context: data-outlet
      dockerfile: Dockerfile
    environment:
      - port=:5000
      - mongo_uri=mongodb://database
