version: "3"
services:
  gateway:
    build:
      context: gateway
      dockerfile: Dockerfile
    environment:
      - port=:5000
      - mongo_uri=mongodb://database
    env_file:
      - .env
    ports:
      - 2865:5000
    links:
      - recommended
      - interactions
      - data-outlet
      - cdn
      - users

  users:
      build:
          context: users 
          dockerfile: Dockerfile
      links:
          - database  
      environment:
          - port=:5000
          - mongo_uri=mongodb://database
  recommended:
    build:
      context: recommendation-service
      dockerfile: Dockerfile
    environment:
      - port=:5000
      - mongo_uri=mongodb://database
    links:
      - database

  interactions:
    build:
      context: interactions
      dockerfile: Dockerfile
    environment:
      - port=:5000
      - mongo_uri=mongodb://database
    links:
      - database

  data-outlet:
    build:
      context: data-outlet
      dockerfile: Dockerfile
    environment:
      - port=:5000
      - mongo_uri=mongodb://database
    links:
      - database

  cdn:
    build:
      context: cdn
      dockerfile: Dockerfile
    environment:
      - port=:5000
      - mongo_uri=mongodb://database
    links:
      - database

  database:
    image: mongo:4.0
    volumes:
      - bluemediadb:/data/db
    ports:
      - 27017:27017
volumes:
  bluemediadb:
